### ISSUE TITLE
F-Droid Version crashes

### ISSUE THREAD

**Issue by Quantenzitrone** [MetatransApps/Android_APK_2DGravity#2]
Model: SHIFT6m
Android Version: 8.1.0

The app doesnt open at all.
It just "stoppes" when I try to open it.

**Comment by dfandrich** [comment]
Attached is a log of the crash: [gravity-bug.log](https://github.com/MetatransApps/Android_APK_2DGravity/files/7451641/gravity-bug.log)  This is with the F-Driod version ver. 1.0.3 on Lineage OS 14.1 (Android 7.1.2).

**Comment by MetatransApps** [comment]
Hi and thanks a lot for the logs!
Looks interesting, this is code gotten from master not from the release tag. The master branch meanwhile was in this state for a few days.
The next update based on this release will work: https://github.com/MetatransApps/Android_APK_2DGravity/releases/tag/107-fdroid-app-update
Best regards,
Krasimir

**Comment by Quantenzitrone** [comment]
I tried out the new version that got released on F-Droid yesterday (it says 1 day ago so) and it works
👍👍

I am not a fan of the game tho which is probably because it is not completly finished. So keep up the great work. We need more people developing open source games.

**Comment by dfandrich** [comment]
The 1.0.7 version in F-Droid also works for me. I've opened https://gitlab.com/fdroid/fdroiddata/-/issues/2522 on F-Droid about building sources from HEAD.

**Comment by MetatransApps** [comment]
Thanks for reporting this issue!
I believe it will be easy to fix with small configuration change ...

3 more games are coming to F-Droid:
https://gitlab.com/fdroid/rfp/-/issues/1897
https://gitlab.com/fdroid/rfp/-/issues/1894
https://gitlab.com/fdroid/rfp/-/issues/1893

One more general question: what kind of games you like and are looing for?

Best regards,
Krasimir

**Comment by linsui** [comment]
F-Droid publishes the source code for every apk so the build process should be able to repro duce. But in the metadata of this app some libraries is cloned without a tag  so that we can't ensure building from the same source code as upstream. Could you please add those repos needed from the build as git submodules? Thanks!

**Comment by MetatransApps** [comment]
Hi and thanks for the prompt reply in this issue!
I have created releases/tags for the lib projects as well, so the build will be now reproducible:
https://github.com/MetatransApps/Android_LIB_Commons/releases/tag/100
https://github.com/MetatransApps/Android_LIB_CommonsAds/releases/tag/100
https://github.com/MetatransApps/Android_LIB_Commons2D/releases/tag/100
https://github.com/MetatransApps/Android_APP_2DGravity/releases/tag/100
Best regards,
Krasimir

**Comment by linsui** [comment]
When should we update the tag?

**Comment by Quantenzitrone** [comment]
> One more general question: what kind of games you like and are looing for?
I am not really a mobile gamer, so none. I juat found the app sounded interesting.
The bug is fixed for everyone, right?
So shall I close this issue?

**Comment by MetatransApps** [comment]
Hi, this is ok from my side.
I will follow-up on the reported issue: https://gitlab.com/fdroid/fdroiddata/-/issues/2522
Thanks a lot for the great collaboration from Your side!
Best regards,
Krasimir
